#! /bin/sh

set -e

# Don't bother
if [ "$IFACE" = lo ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

if [ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]; then
	exit 0
fi

if [ "$IFACE" = wlan0 ]; then
	cp /etc/NetworkManager/system-connections/* /boot/config/network/
fi

exit 0
